// Editor state = exactly the script.json content. Every action produces the
// next valid script.json — malformed scripts are impossible by construction.
//
// Invariants (project spec §5.1):
//  - line and character ids are UUIDs, minted once and NEVER reused;
//  - ids are UNIQUE and match SAFE_ID (they become clip filenames — the
//    GitHub Action enforces the same pattern, see scripts/process_uploads.py);
//  - moving/editing a line keeps its id; only ADD_LINE mints a new id;
//  - a line references its character by characterId, never by name.
//
// UUIDs are generated by the EVENT HANDLERS (newId()) and carried in the
// action, never inside the reducer: reducers must stay pure (React may
// replay them). Exception: sanitizeScript may remint ids, but it only runs
// on LOAD_SCRIPT to repair hand-edited files.

import { firstFreeColor, isPaletteColor } from "../shared/characterColors.js";

export function newId() {
  return crypto.randomUUID();
}

// Mirror of LINE_ID_PATTERN in scripts/process_uploads.py — keep in sync.
export const SAFE_ID = /^[0-9a-zA-Z-]{1,64}$/;

export const EMPTY_SCRIPT = {
  title: "",
  characters: [],
  acts: [{ title: "Acte I", scenes: [{ title: "Scène 1", lines: [] }] }],
};

const isId = (value) => typeof value === "string" && SAFE_ID.test(value);

// Defensive normalization of a loaded script.json (the published file can be
// hand-edited on github.com): fills missing fields, drops malformed entries,
// and heals invalid or DUPLICATED ids by minting fresh UUIDs — duplicate ids
// would corrupt React keys, dnd-kit sorting and status computation.
export function sanitizeScript(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) raw = {};

  const seenIds = new Set();
  // Personnage reminté parce que son id était HORS SAFE_ID : ancien -> neuf,
  // pour que ses répliques le suivent. Uniquement ce cas-là.
  //
  // Un id DUPLIQUÉ ne s'y inscrit pas, et c'est la moitié qui compte : le
  // premier porteur garde l'id, donc les répliques qui le citent lui restent,
  // et le second repart avec un id neuf et aucune réplique. Remapper ici
  // enverrait les répliques du premier au second, c'est-à-dire changerait qui
  // parle dans la pièce (les mp3, eux, sont nommés par id de réplique et ne
  // bougent pas : la voix d'Alceste se mettrait à sortir sous le nom de
  // Philinte). Entre deux personnages indiscernables dans le fichier, on ne
  // déplace rien.
  const characterRemap = new Map();

  const usedColors = new Set();
  // Compte des personnages déjà servis, distinct de `usedColors.size`, qui cesse
  // de grandir dès la palette épuisée : cf. `firstFreeColor`.
  let assignedColors = 0;
  const characters = (Array.isArray(raw.characters) ? raw.characters : [])
    .filter((c) => c && typeof c === "object" && typeof c.name === "string" && c.name.trim())
    .map((c) => {
      let id = c.id;
      if (!isId(id) || seenIds.has(id)) {
        const fresh = newId();
        // Reminté pour cause d'id invalide (et non de doublon) : cet id-là
        // n'est porté que par lui, ses répliques peuvent le suivre sans
        // ambiguïté. Cf. le commentaire de characterRemap.
        if (!isId(id) && typeof id === "string" && id) characterRemap.set(id, fresh);
        id = fresh;
      }
      seenIds.add(id);
      // Comble une couleur absente, étrangère ou déjà prise par la première
      // libre (déterministe). Même comblement qu'`assignColors` du module
      // partagé, que les pages qui lisent le manifest appliquent de leur côté :
      // les deux doivent tomber d'accord sur un script sans couleurs.
      const color =
        isPaletteColor(c.color) && !usedColors.has(c.color.toLowerCase())
          ? c.color.toLowerCase()
          : firstFreeColor(usedColors, assignedColors);
      usedColors.add(color);
      assignedColors += 1;
      return { id, name: c.name, color };
    });
  const characterIds = new Set(characters.map((c) => c.id));

  const sanitizeLine = (l) => {
    if (!l || typeof l !== "object") return null;
    let id = l.id;
    if (!isId(id) || seenIds.has(id)) id = newId();
    seenIds.add(id);
    // Le remap se consulte sur la valeur BRUTE, avant tout contrôle contre
    // SAFE_ID : les ids qu'il contient sont justement ceux qui ne le passent
    // pas. Les valider d'abord (ce que faisait ce code) revenait à ne jamais
    // le consulter, et les répliques d'un personnage reminté devenaient
    // orphelines pour une lettre accentuée dans le fichier.
    let characterId = typeof l.characterId === "string" ? l.characterId : null;
    if (characterId && characterRemap.has(characterId)) characterId = characterRemap.get(characterId);
    // characterIds ne contient que des ids valides : cette seule appartenance
    // rejette aussi bien un id hors SAFE_ID qu'un personnage inexistant.
    if (characterId && !characterIds.has(characterId)) characterId = null;
    return { id, characterId, text: typeof l.text === "string" ? l.text : "" };
  };

  return {
    title: typeof raw.title === "string" ? raw.title : "",
    characters,
    acts:
      Array.isArray(raw.acts) && raw.acts.length > 0
        ? raw.acts
            .filter((act) => act && typeof act === "object")
            .map((act, ai) => ({
              title: typeof act.title === "string" ? act.title : `Acte ${ai + 1}`,
              scenes:
                Array.isArray(act.scenes) && act.scenes.length > 0
                  ? act.scenes
                      .filter((scene) => scene && typeof scene === "object")
                      .map((scene, si) => ({
                        title: typeof scene.title === "string" ? scene.title : `Scène ${si + 1}`,
                        lines: Array.isArray(scene.lines)
                          ? scene.lines.map(sanitizeLine).filter(Boolean)
                          : [],
                      }))
                  : [{ title: "Scène 1", lines: [] }],
            }))
        : EMPTY_SCRIPT.acts,
  };
}

export function allLines(script) {
  return script.acts.flatMap((a) => a.scenes.flatMap((s) => s.lines));
}

// Character of a line inserted after index `idx` in `scene`: the SAME
// character as the line it follows (Enter continues the current speaker);
// falls back to the play's first character.
function defaultCharacterId(scene, idx, characters) {
  return scene.lines[idx]?.characterId ?? characters[0]?.id ?? null;
}

// Immutably update one scene designated by indices. Only that scene's
// object changes identity — untouched acts/scenes keep theirs, which is what
// lets React.memo skip re-rendering the rest of the play on every keystroke.
//
// Quand `fn` rend la scène telle quelle (l'action ne changeait rien), on rend
// l'ÉTAT tel quel. Sans cette sortie, un no-op fabriquait quand même un nouvel
// objet d'état : history.js, qui reconnaît une action refusée à l'identité
// (`present === state.present`), y voyait une vraie modification. Reposer une
// réplique glissée exactement où elle était allumait donc « Modifications non
// téléchargées » sans qu'on ait rien modifié, et laissait une étape vide à
// annuler. Idem pour des indices hors bornes, qui ne désignent aucune scène.
function updateScene(state, actIndex, sceneIndex, fn) {
  const act = state.acts[actIndex];
  const scene = act?.scenes?.[sceneIndex];
  if (!scene) return state;
  const nextScene = fn(scene);
  if (nextScene === scene) return state;
  return {
    ...state,
    acts: state.acts.map((act, ai) =>
      ai !== actIndex
        ? act
        : {
            ...act,
            scenes: act.scenes.map((s, si) => (si !== sceneIndex ? s : nextScene)),
          }
    ),
  };
}

// Immutably update every line of the script (rare, character-level ops only).
function mapAllLines(state, fn) {
  return {
    ...state,
    acts: state.acts.map((act) => ({
      ...act,
      scenes: act.scenes.map((scene) => ({
        ...scene,
        lines: scene.lines.map(fn).filter(Boolean),
      })),
    })),
  };
}

// Applique un lot de textes de répliques (`[{ lineId, text }]`) en UN état.
//
// Deux choses la distinguent de mapAllLines, qui reconstruit toujours tout :
//  - elle rend l'état PRÉCIS reçu quand aucune édition ne change quoi que ce
//    soit (lot vide, id inconnu, texte identique, lot malformé). history.js
//    reconnaît une action sans effet à l'identité, donc sans cette sortie un
//    « Tout remplacer » sans occurrence laisserait une étape vide à annuler et
//    allumerait « Modifications non téléchargées » ;
//  - elle garde l'identité des actes, des scènes et des répliques intacts, donc
//    React.memo continue de sauter tout ce que le remplacement n'a pas touché.
//
// Les ids de réplique étant uniques dans TOUTE la pièce (sanitizeScript le
// garantit, ADD_LINE mint un UUID), une Map par id suffit : pas d'indices
// d'acte ni de scène dans le lot.
function applyTextEdits(state, edits) {
  if (!Array.isArray(edits) || edits.length === 0) return state;
  const byLine = new Map();
  for (const edit of edits) {
    // Le lot vient du navigateur, pas d'un fichier : une entrée malformée est
    // un bug d'appelant, on l'ignore plutôt que de jeter au milieu d'un
    // remplacement à moitié appliqué.
    if (edit && typeof edit.lineId === "string" && typeof edit.text === "string") {
      byLine.set(edit.lineId, edit.text);
    }
  }
  if (byLine.size === 0) return state;

  let changed = false;
  const acts = state.acts.map((act) => {
    let actChanged = false;
    const scenes = act.scenes.map((scene) => {
      let sceneChanged = false;
      const lines = scene.lines.map((line) => {
        if (!byLine.has(line.id)) return line;
        const text = byLine.get(line.id);
        if (text === line.text) return line;
        sceneChanged = true;
        return { ...line, text };
      });
      if (!sceneChanged) return scene;
      actChanged = true;
      return { ...scene, lines };
    });
    if (!actChanged) return act;
    changed = true;
    return { ...act, scenes };
  });
  return changed ? { ...state, acts } : state;
}

// Copie du tableau avec l'élément `from` posé en `to`, ou `null` quand il n'y a
// rien à faire (indices hors bornes, ou déplacement sur place). Le `null` n'est
// pas de la coquetterie : les deux appelants rendent alors l'état PRÉCIS reçu, et
// c'est ce qui empêche une scène reposée là où elle était d'allumer
// « Modifications non téléchargées » et de laisser une étape vide à annuler
// (même règle que updateScene, cf. son commentaire).
function moved(list, from, to) {
  const ok = (i) => Number.isInteger(i) && i >= 0 && i < list.length;
  if (!ok(from) || !ok(to) || from === to) return null;
  const next = [...list];
  const [item] = next.splice(from, 1);
  next.splice(to, 0, item);
  return next;
}

// ---- Où regarder après un remaniement du plan ----
//
// L'éditeur montre une scène à la fois, désignée par deux rangs. Déplacer ou
// supprimer un acte ou une scène change les rangs de ses voisins, donc sans ces
// deux fonctions le même couple d'indices ne désigne plus la même scène : glisser
// l'acte III au-dessus de l'acte I pendant qu'on y travaille faisait sauter la
// colonne de texte sur un autre acte. Elles sont ici, à côté de MOVE_* et
// DELETE_*, parce qu'elles décrivent exactement la permutation que ces actions
// appliquent : les faire diverger est le bug qu'on cherche à éviter.

// Rang de suivi d'un élément après le déplacement `from` -> `to` : celui qui
// bouge suit, ceux que sa traversée décale d'un cran se décalent d'un cran.
export function indexAfterMove(index, from, to) {
  if (index === from) return to;
  if (from < index && index <= to) return index - 1;
  if (to <= index && index < from) return index + 1;
  return index;
}

// Rang de suivi après la suppression de `removed`. Quand c'est l'élément regardé
// qui disparaît, on regarde le précédent (et non le suivant, qui a pris son
// rang) : c'est celui qu'on avait sous les yeux avant lui, donc le retour en
// arrière que le geste laisse attendre.
export function indexAfterRemoval(index, removed) {
  if (index === removed) return Math.max(0, removed - 1);
  return index > removed ? index - 1 : index;
}

export function scriptReducer(state, action) {
  switch (action.type) {
    case "LOAD_SCRIPT":
      return sanitizeScript(action.script);

    case "SET_TITLE":
      return { ...state, title: action.title };

    // ---- Characters (side panel referential) ----

    case "ADD_CHARACTER": {
      // action.id: UUID minted by the caller. Couleur : la première libre (pure,
      // lue dans l'état).
      const name = action.name.trim();
      if (!name) return state;
      const color = firstFreeColor(
        new Set(state.characters.map((c) => c.color)),
        state.characters.length
      );
      return {
        ...state,
        characters: [...state.characters, { id: action.id, name, color }],
      };
    }

    case "SET_CHARACTER_COLOR":
      if (!isPaletteColor(action.color)) return state;
      return {
        ...state,
        characters: state.characters.map((c) =>
          c.id === action.id ? { ...c, color: action.color } : c
        ),
      };

    case "RENAME_CHARACTER": {
      const name = action.name.trim();
      if (!name) return state;
      // Renaming only touches the referential — no line id changes, so no
      // recording ever becomes stale because of a rename.
      return {
        ...state,
        characters: state.characters.map((c) => (c.id === action.id ? { ...c, name } : c)),
      };
    }

    case "DELETE_CHARACTER": {
      // action.mode: "reassign" (to action.reassignTo) or "deleteLines".
      // Characters with no lines can be deleted with either mode.
      let next = state;
      if (action.mode === "reassign" && action.reassignTo != null) {
        next = mapAllLines(next, (l) =>
          l.characterId === action.id ? { ...l, characterId: action.reassignTo } : l
        );
      } else {
        next = mapAllLines(next, (l) => (l.characterId === action.id ? null : l));
      }
      return {
        ...next,
        characters: next.characters.filter((c) => c.id !== action.id),
      };
    }

    // ---- Acts & scenes ----

    case "ADD_ACT":
      return {
        ...state,
        acts: [
          ...state.acts,
          { title: `Acte ${state.acts.length + 1}`, scenes: [{ title: "Scène 1", lines: [] }] },
        ],
      };

    case "RENAME_ACT":
      return {
        ...state,
        acts: state.acts.map((a, i) => (i === action.actIndex ? { ...a, title: action.title } : a)),
      };

    case "DELETE_ACT":
      return { ...state, acts: state.acts.filter((_, i) => i !== action.actIndex) };

    case "ADD_SCENE":
      return {
        ...state,
        acts: state.acts.map((a, i) =>
          i !== action.actIndex
            ? a
            : { ...a, scenes: [...a.scenes, { title: `Scène ${a.scenes.length + 1}`, lines: [] }] }
        ),
      };

    case "RENAME_SCENE":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        title: action.title,
      }));

    case "DELETE_SCENE":
      return {
        ...state,
        acts: state.acts.map((a, i) =>
          i !== action.actIndex ? a : { ...a, scenes: a.scenes.filter((_, si) => si !== action.sceneIndex) }
        ),
      };

    // Réordonner le plan de la pièce (section « Structure » du rail). Les actes
    // et les scènes n'ont pas d'id, ils sont désignés par leur rang : un
    // déplacement est donc un couple d'indices, et non deux ids comme MOVE_LINE.
    // Ça ne coûte rien ici, les indices ne bougent pas pendant un glissement, et
    // les répliques déplacées avec leur scène gardent les leurs (donc leurs mp3).
    //
    // Une scène ne change pas d'acte : la borner à son acte est ce qui garde
    // l'action à un seul indice de conteneur, et un glissement d'un acte à
    // l'autre demanderait de choisir en plus où elle atterrit dans l'acte
    // d'arrivée. Le geste manquant est la découpe d'un acte, qui se fait
    // aujourd'hui en ajoutant l'acte puis en redéplaçant les répliques.
    case "MOVE_ACT": {
      const acts = moved(state.acts, action.from, action.to);
      return acts ? { ...state, acts } : state;
    }

    case "MOVE_SCENE": {
      const act = state.acts[action.actIndex];
      if (!act) return state;
      const scenes = moved(act.scenes, action.from, action.to);
      if (!scenes) return state;
      return {
        ...state,
        acts: state.acts.map((a, i) => (i !== action.actIndex ? a : { ...a, scenes })),
      };
    }

    // ---- Lines (all scoped to one scene: O(scene), not O(whole play)) ----

    case "ADD_LINE": {
      // Insert after line `afterLineId` (or append when null).
      // action.id: UUID minted by the caller (which also uses it to focus
      // the new line's textarea). The default character (same speaker as
      // the previous line) is computed here — pure, from state + action only.
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const idx =
          action.afterLineId == null
            ? scene.lines.length - 1
            : scene.lines.findIndex((l) => l.id === action.afterLineId);
        const newLine = {
          id: action.id,
          characterId: defaultCharacterId(scene, idx, state.characters),
          text: "",
        };
        const lines = [...scene.lines];
        lines.splice(idx + 1, 0, newLine);
        return { ...scene, lines };
      });
    }

    case "EDIT_TEXT":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const line = scene.lines.find((l) => l.id === action.lineId);
        // Texte inchangé (ou réplique disparue) : on rend la scène telle quelle,
        // et updateScene rend donc l'état tel quel. Sans ça, `map` allouait
        // toujours une nouvelle scène, history.js y voyait une vraie
        // modification, et une frappe qui ne change rien (un remplacement au
        // texte identique, une valeur reposée par du code) laissait une étape
        // vide à annuler et allumait « Modifications non téléchargées ».
        if (!line || line.text === action.text) return scene;
        return {
          ...scene,
          lines: scene.lines.map((l) => (l.id === action.lineId ? { ...l, text: action.text } : l)),
        };
      });

    // Un lot de textes de répliques, à travers TOUTE la pièce : le remplacement
    // de la recherche (une occurrence ou toutes). Seul cas « lignes » qui n'est
    // pas borné à une scène, exprès, un remplacement traversant la pièce.
    // Nommé d'après ce qu'il fait au script et pas d'après la fonctionnalité :
    // le reducer ne sait rien d'une recherche.
    case "SET_LINE_TEXTS":
      return applyTextEdits(state, action.edits);

    case "SET_LINE_CHARACTER":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.map((l) =>
          l.id === action.lineId ? { ...l, characterId: action.characterId } : l
        ),
      }));

    case "DELETE_LINE":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.filter((l) => l.id !== action.lineId),
      }));

    case "MOVE_LINE": {
      // Reorder within a scene: the moved line keeps its id (ids travel with
      // the object).
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const from = scene.lines.findIndex((l) => l.id === action.activeId);
        const to = scene.lines.findIndex((l) => l.id === action.overId);
        if (from === -1 || to === -1 || from === to) return scene;
        const lines = [...scene.lines];
        const [moved] = lines.splice(from, 1);
        lines.splice(to, 0, moved);
        return { ...scene, lines };
      });
    }

    default:
      return state;
  }
}
