// Editor state = exactly the script.json content. Every action produces the
// next valid script.json, malformed scripts are impossible by construction.
//
// Invariants (project spec §5.1):
//  - line and character ids are UUIDs, minted once and NEVER reused;
//  - ids are UNIQUE and match SAFE_ID (they become clip filenames, the
//    GitHub Action enforces the same pattern, see scripts/process_uploads.py);
//  - moving/editing a line keeps its id; only ADD_LINE mints a new id;
//  - a line references its character by characterId, never by name.
//
// UUIDs are generated by the EVENT HANDLERS (newId()) and carried in the
// action, never inside the reducer: reducers must stay pure (React may
// replay them). Exception: sanitizeScript may remint ids, but it only runs
// on LOAD_SCRIPT to repair hand-edited files.

import { firstFreeColor, isPaletteColor } from "../shared/characterColors.js";
// i18n.js is pure (no React, no DOM, no storage), so importing it here keeps
// this module runnable under `node --test`. locale.js would NOT be safe: it
// reads `window` at module load.
import { DEFAULT_LOCALE, isLocale } from "../shared/i18n.js";
// Pure as well (it only carries one expression and its test), so safe for
// `node --test`: see src/shared/plays.js.
import { isPlayId } from "../shared/plays.js";

export function newId() {
  return crypto.randomUUID();
}

// Mirror of LINE_ID_PATTERN in scripts/process_uploads.py, keep in sync.
export const SAFE_ID = /^[0-9a-zA-Z-]{1,64}$/;

// Acts and scenes carry NO title. Their label is derived from their rank at
// render time ("Acte I", "Scène 3"), which is why nothing here writes words into
// the play: a title stored in script.json would be data in one language, and it
// would then have to travel to the manifest, the PDF, the Progress columns and
// the Speaking share scope, none of which could translate it. Deriving the label
// makes it ordinary UI text instead.
//
// The cost, accepted: an act cannot be called "Prologue". If that comes back, it
// is an optional field to add, not a redesign.
//
// `language` is the language the PLAY is written in, a different axis from the
// reader's UI locale. It is set in the Structure section of the rail, and it is
// what lets build_script_pdf.py compose its own headings and set its babel, and
// useTts.js pick a voice that matches the dialogue.
// `id` is the play's identifier, the one that names its folder in the repo
// (`plays/<id>/`) and its upload area (`uploads/<id>/`), see src/shared/plays.js.
// The editor NEVER mints it nor modifies it: it receives it with the script and
// returns it as is in the downloaded file, which is what lets the Action know which
// play this upload updates. It is empty here because EMPTY_SCRIPT is the fallback of
// a page that has not read a script yet; it is the play management page that mints
// the identifier, once, at creation time.
export const EMPTY_SCRIPT = {
  id: "",
  title: "",
  language: DEFAULT_LOCALE,
  characters: [],
  acts: [{ scenes: [{ lines: [] }] }],
};

const isId = (value) => typeof value === "string" && SAFE_ID.test(value);

// Defensive normalization of a loaded script.json (the published file can be
// hand-edited on github.com): fills missing fields, drops malformed entries,
// and heals invalid or DUPLICATED ids by minting fresh UUIDs, duplicate ids
// would corrupt React keys, dnd-kit sorting and status computation.
export function sanitizeScript(raw) {
  if (raw === null || typeof raw !== "object" || Array.isArray(raw)) raw = {};

  const seenIds = new Set();
  // Character reminted because its id was OUTSIDE SAFE_ID: old -> new, so that its
  // lines follow it. That case only.
  //
  // A DUPLICATED id is not entered here, and that is the half that matters: the
  // first bearer keeps the id, so the lines that cite it stay with it, and the
  // second one leaves with a fresh id and no lines. Remapping here would send the
  // first one's lines to the second, that is to say would change who speaks in the
  // play (the mp3s, for their part, are named by line id and do not move: Alceste's
  // voice would start coming out under Philinte's name). Between two characters that
  // are indistinguishable in the file, we move nothing.
  const characterRemap = new Map();

  const usedColors = new Set();
  // Count of characters already served, distinct from `usedColors.size`, which stops
  // growing as soon as the palette is exhausted: see `firstFreeColor`.
  let assignedColors = 0;
  const characters = (Array.isArray(raw.characters) ? raw.characters : [])
    .filter((c) => c && typeof c === "object" && typeof c.name === "string" && c.name.trim())
    .map((c) => {
      let id = c.id;
      if (!isId(id) || seenIds.has(id)) {
        const fresh = newId();
        // Reminted because of an invalid id (and not of a duplicate): that id is
        // borne by it alone, its lines can follow it without ambiguity. See the
        // comment on characterRemap.
        if (!isId(id) && typeof id === "string" && id) characterRemap.set(id, fresh);
        id = fresh;
      }
      seenIds.add(id);
      // Fills in a colour that is absent, foreign or already taken with the first
      // free one (deterministic). The same filling in as `assignColors` from the
      // shared module, which the pages that read the manifest apply on their side:
      // the two must agree on a script with no colours.
      const color =
        isPaletteColor(c.color) && !usedColors.has(c.color.toLowerCase())
          ? c.color.toLowerCase()
          : firstFreeColor(usedColors, assignedColors);
      usedColors.add(color);
      assignedColors += 1;
      return { id, name: c.name, color };
    });
  const characterIds = new Set(characters.map((c) => c.id));

  const sanitizeLine = (l) => {
    if (!l || typeof l !== "object") return null;
    let id = l.id;
    if (!isId(id) || seenIds.has(id)) id = newId();
    seenIds.add(id);
    // The remap is consulted on the RAW value, before any check against SAFE_ID:
    // the ids it contains are precisely the ones that do not pass it. Validating
    // them first (which this code used to do) amounted to never consulting it, and
    // the lines of a reminted character became orphans over one accented letter in
    // the file.
    let characterId = typeof l.characterId === "string" ? l.characterId : null;
    if (characterId && characterRemap.has(characterId)) characterId = characterRemap.get(characterId);
    // characterIds only contains valid ids: this single membership test rejects an id
    // outside SAFE_ID just as well as a character that does not exist.
    if (characterId && !characterIds.has(characterId)) characterId = null;
    return { id, characterId, text: typeof l.text === "string" ? l.text : "" };
  };

  return {
    // The play's identifier is COPIED, never reminted, unlike the line and character
    // ids just above: it names the play's folder and its upload area, so minting a
    // fresh one here would send the next downloaded script off to a play that does
    // not exist, leaving behind it the mp3s already uploaded. A file written before
    // this field existed, or hand-edited badly, yields an empty string: the Action
    // will refuse to promote it rather than guess its destination.
    id: isPlayId(raw.id) ? raw.id : "",
    title: typeof raw.title === "string" ? raw.title : "",
    // An unknown or absent language falls back to French, the project's default.
    // A script.json written before this field existed therefore keeps working.
    language: isLocale(raw.language) ? raw.language : DEFAULT_LOCALE,
    characters,
    acts:
      Array.isArray(raw.acts) && raw.acts.length > 0
        ? raw.acts
            .filter((act) => act && typeof act === "object")
            .map((act) => ({
              // A `title` left over from an older file is DROPPED, not carried:
              // labels are derived from the rank now, and keeping a stale one
              // would put two ways of naming a scene back in the format.
              scenes:
                Array.isArray(act.scenes) && act.scenes.length > 0
                  ? act.scenes
                      .filter((scene) => scene && typeof scene === "object")
                      .map((scene) => ({
                        lines: Array.isArray(scene.lines)
                          ? scene.lines.map(sanitizeLine).filter(Boolean)
                          : [],
                      }))
                  : [{ lines: [] }],
            }))
        : EMPTY_SCRIPT.acts,
  };
}

export function allLines(script) {
  return script.acts.flatMap((a) => a.scenes.flatMap((s) => s.lines));
}

// Character of a line inserted after index `idx` in `scene`: the SAME
// character as the line it follows (Enter continues the current speaker);
// falls back to the play's first character.
function defaultCharacterId(scene, idx, characters) {
  return scene.lines[idx]?.characterId ?? characters[0]?.id ?? null;
}

// Immutably update one scene designated by indices. Only that scene's
// object changes identity, untouched acts/scenes keep theirs, which is what
// lets React.memo skip re-rendering the rest of the play on every keystroke.
//
// When `fn` returns the scene as is (the action changed nothing), we return the
// STATE as is. Without that exit, a no-op still manufactured a new state object:
// history.js, which recognises a refused action by identity (`present ===
// state.present`), saw a real modification in it. Dropping a dragged line exactly
// where it already was therefore lit "Changes not downloaded" without anything
// having been modified, and left an empty step to undo. Same for out-of-bounds
// indices, which designate no scene.
function updateScene(state, actIndex, sceneIndex, fn) {
  const act = state.acts[actIndex];
  const scene = act?.scenes?.[sceneIndex];
  if (!scene) return state;
  const nextScene = fn(scene);
  if (nextScene === scene) return state;
  return {
    ...state,
    acts: state.acts.map((act, ai) =>
      ai !== actIndex
        ? act
        : {
            ...act,
            scenes: act.scenes.map((s, si) => (si !== sceneIndex ? s : nextScene)),
          }
    ),
  };
}

// Immutably update every line of the script (rare, character-level ops only).
function mapAllLines(state, fn) {
  return {
    ...state,
    acts: state.acts.map((act) => ({
      ...act,
      scenes: act.scenes.map((scene) => ({
        ...scene,
        lines: scene.lines.map(fn).filter(Boolean),
      })),
    })),
  };
}

// Applies a batch of line texts (`[{ lineId, text }]`) in ONE state.
//
// Two things set it apart from mapAllLines, which always rebuilds everything:
//  - it returns the EXACT state it received when no edit changes anything at all
//    (empty batch, unknown id, identical text, malformed batch). history.js
//    recognises an action with no effect by identity, so without that exit a
//    "Replace all" with no match would leave an empty step to undo and would light
//    "Changes not downloaded";
//  - it keeps the identity of the acts, scenes and lines intact, so React.memo keeps
//    skipping everything the replacement did not touch.
//
// Since line ids are unique across the WHOLE play (sanitizeScript guarantees it,
// ADD_LINE mints a UUID), a Map keyed by id is enough: no act or scene indices in the
// batch.
function applyTextEdits(state, edits) {
  if (!Array.isArray(edits) || edits.length === 0) return state;
  const byLine = new Map();
  for (const edit of edits) {
    // The batch comes from the browser, not from a file: a malformed entry is a
    // caller bug, we ignore it rather than throw in the middle of a half-applied
    // replacement.
    if (edit && typeof edit.lineId === "string" && typeof edit.text === "string") {
      byLine.set(edit.lineId, edit.text);
    }
  }
  if (byLine.size === 0) return state;

  let changed = false;
  const acts = state.acts.map((act) => {
    let actChanged = false;
    const scenes = act.scenes.map((scene) => {
      let sceneChanged = false;
      const lines = scene.lines.map((line) => {
        if (!byLine.has(line.id)) return line;
        const text = byLine.get(line.id);
        if (text === line.text) return line;
        sceneChanged = true;
        return { ...line, text };
      });
      if (!sceneChanged) return scene;
      actChanged = true;
      return { ...scene, lines };
    });
    if (!actChanged) return act;
    changed = true;
    return { ...act, scenes };
  });
  return changed ? { ...state, acts } : state;
}

// A copy of the array with the `from` element placed at `to`, or `null` when there
// is nothing to do (out-of-bounds indices, or a move in place). The `null` is not
// affectation: the two callers then return the EXACT state they received, and that is
// what stops a scene dropped back where it already was from lighting "Changes not
// downloaded" and leaving an empty step to undo (same rule as updateScene, see its
// comment).
function moved(list, from, to) {
  const ok = (i) => Number.isInteger(i) && i >= 0 && i < list.length;
  if (!ok(from) || !ok(to) || from === to) return null;
  const next = [...list];
  const [item] = next.splice(from, 1);
  next.splice(to, 0, item);
  return next;
}

// ---- Where to look after the plan has been reshuffled ----
//
// The editor shows one scene at a time, designated by two ranks. Moving or deleting
// an act or a scene changes the ranks of its neighbours, so without these two
// functions the same pair of indices no longer designates the same scene: dragging
// act III above act I while working in it made the text column jump to another act.
// They are here, next to MOVE_* and DELETE_*, because they describe exactly the
// permutation those actions apply: making them diverge is the bug we are trying to
// avoid.

// Follow-up rank of an element after the `from` -> `to` move: the one that moves
// follows, those its crossing shifts by one notch shift by one notch.
export function indexAfterMove(index, from, to) {
  if (index === from) return to;
  if (from < index && index <= to) return index - 1;
  if (to <= index && index < from) return index + 1;
  return index;
}

// Follow-up rank after the deletion of `removed`. When it is the element being looked
// at that disappears, we look at the previous one (and not at the next, which has
// taken its rank): it is the one that was in front of us before it, hence the step
// backwards that the gesture leads one to expect.
export function indexAfterRemoval(index, removed) {
  if (index === removed) return Math.max(0, removed - 1);
  return index > removed ? index - 1 : index;
}

export function scriptReducer(state, action) {
  switch (action.type) {
    case "LOAD_SCRIPT":
      return sanitizeScript(action.script);

    // The equality guard is not defensive, it is the "a no-op must not manufacture a
    // new state" invariant, and it holds here for the same reason as in
    // `SET_LANGUAGE` just below. A title put back identically does happen (Ctrl+A
    // then pasting the same text: the event fires, the value is the same), and
    // without it the step was pushed all the same, with a `present` equal to its
    // `past`, hence a Ctrl+Z that lights up and changes nothing on screen. Since
    // `asSavedIfUnchanged` (history.js) the case moreover read in two contradictory
    // places: the "Changes not downloaded" label stayed off, which is right, below a
    // lit undo button.
    case "SET_TITLE":
      if (action.title === state.title) return state;
      return { ...state, title: action.title };

    // The language the PLAY is written in, not the reader's UI locale. It drives
    // the PDF (headings and babel) and the synthetic voice that stands in for a
    // line nobody has recorded yet.
    case "SET_LANGUAGE":
      if (!isLocale(action.language) || action.language === state.language) return state;
      return { ...state, language: action.language };

    // ---- Characters (side panel referential) ----

    case "ADD_CHARACTER": {
      // action.id: UUID minted by the caller. Colour: the first free one (pure, read
      // from the state).
      const name = action.name.trim();
      if (!name) return state;
      const color = firstFreeColor(
        new Set(state.characters.map((c) => c.color)),
        state.characters.length
      );
      return {
        ...state,
        characters: [...state.characters, { id: action.id, name, color }],
      };
    }

    case "SET_CHARACTER_COLOR":
      if (!isPaletteColor(action.color)) return state;
      return {
        ...state,
        characters: state.characters.map((c) =>
          c.id === action.id ? { ...c, color: action.color } : c
        ),
      };

    case "RENAME_CHARACTER": {
      const name = action.name.trim();
      if (!name) return state;
      // Renaming only touches the referential, no line id changes, so no
      // recording ever becomes stale because of a rename.
      return {
        ...state,
        characters: state.characters.map((c) => (c.id === action.id ? { ...c, name } : c)),
      };
    }

    case "DELETE_CHARACTER": {
      // action.mode: "reassign" (to action.reassignTo) or "deleteLines".
      // Characters with no lines can be deleted with either mode.
      let next = state;
      if (action.mode === "reassign" && action.reassignTo != null) {
        next = mapAllLines(next, (l) =>
          l.characterId === action.id ? { ...l, characterId: action.reassignTo } : l
        );
      } else {
        next = mapAllLines(next, (l) => (l.characterId === action.id ? null : l));
      }
      return {
        ...next,
        characters: next.characters.filter((c) => c.id !== action.id),
      };
    }

    // ---- Acts & scenes ----

    case "ADD_ACT":
      return { ...state, acts: [...state.acts, { scenes: [{ lines: [] }] }] };

    case "DELETE_ACT":
      return { ...state, acts: state.acts.filter((_, i) => i !== action.actIndex) };

    case "ADD_SCENE":
      return {
        ...state,
        acts: state.acts.map((a, i) =>
          i !== action.actIndex ? a : { ...a, scenes: [...a.scenes, { lines: [] }] }
        ),
      };

    case "DELETE_SCENE":
      return {
        ...state,
        acts: state.acts.map((a, i) =>
          i !== action.actIndex ? a : { ...a, scenes: a.scenes.filter((_, si) => si !== action.sceneIndex) }
        ),
      };

    // Reordering the play's plan (the rail's "Structure" section). Acts and scenes
    // have no id, they are designated by their rank: a move is therefore a pair of
    // indices, and not two ids like MOVE_LINE. That costs nothing here, the indices
    // do not move during a drag, and the lines moved along with their scene keep
    // theirs (hence their mp3s).
    //
    // A scene does not change act: bounding it to its act is what keeps the action to
    // a single container index, and a drag from one act to another would require
    // choosing in addition where it lands in the destination act. The missing gesture
    // is splitting an act, which is done today by adding the act then moving the
    // lines across again.
    case "MOVE_ACT": {
      const acts = moved(state.acts, action.from, action.to);
      return acts ? { ...state, acts } : state;
    }

    case "MOVE_SCENE": {
      const act = state.acts[action.actIndex];
      if (!act) return state;
      const scenes = moved(act.scenes, action.from, action.to);
      if (!scenes) return state;
      return {
        ...state,
        acts: state.acts.map((a, i) => (i !== action.actIndex ? a : { ...a, scenes })),
      };
    }

    // ---- Lines (all scoped to one scene: O(scene), not O(whole play)) ----

    case "ADD_LINE": {
      // Insert after line `afterLineId` (or append when null).
      // action.id: UUID minted by the caller (which also uses it to focus
      // the new line's textarea). The default character (same speaker as
      // the previous line) is computed here: pure, from state + action only.
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const idx =
          action.afterLineId == null
            ? scene.lines.length - 1
            : scene.lines.findIndex((l) => l.id === action.afterLineId);
        const newLine = {
          id: action.id,
          characterId: defaultCharacterId(scene, idx, state.characters),
          text: "",
        };
        const lines = [...scene.lines];
        lines.splice(idx + 1, 0, newLine);
        return { ...scene, lines };
      });
    }

    case "EDIT_TEXT":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const line = scene.lines.find((l) => l.id === action.lineId);
        // Text unchanged (or line gone): we return the scene as is, and updateScene
        // therefore returns the state as is. Without this, `map` always allocated a
        // new scene, history.js saw a real modification in it, and a keystroke that
        // changes nothing (a replacement with identical text, a value put back by
        // code) left an empty step to undo and lit "Changes not downloaded".
        if (!line || line.text === action.text) return scene;
        return {
          ...scene,
          lines: scene.lines.map((l) => (l.id === action.lineId ? { ...l, text: action.text } : l)),
        };
      });

    // A batch of line texts, across the WHOLE play: the search's replacement (one
    // match or all of them). The only "lines" case that is not bounded to one scene,
    // on purpose, since a replacement crosses the play. Named after what it does to
    // the script and not after the feature: the reducer knows nothing about a
    // search.
    case "SET_LINE_TEXTS":
      return applyTextEdits(state, action.edits);

    case "SET_LINE_CHARACTER":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.map((l) =>
          l.id === action.lineId ? { ...l, characterId: action.characterId } : l
        ),
      }));

    case "DELETE_LINE":
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => ({
        ...scene,
        lines: scene.lines.filter((l) => l.id !== action.lineId),
      }));

    case "MOVE_LINE": {
      // Reorder within a scene: the moved line keeps its id (ids travel with
      // the object).
      return updateScene(state, action.actIndex, action.sceneIndex, (scene) => {
        const from = scene.lines.findIndex((l) => l.id === action.activeId);
        const to = scene.lines.findIndex((l) => l.id === action.overId);
        if (from === -1 || to === -1 || from === to) return scene;
        const lines = [...scene.lines];
        const [moved] = lines.splice(from, 1);
        lines.splice(to, 0, moved);
        return { ...scene, lines };
      });
    }

    default:
      return state;
  }
}
